name: Checkmarx One Manifest Parser

on:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go version
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - run: go version
      - name: go test with coverage
        run: |
          go test ./... -timeout 25m -coverprofile cover.out
      - name: Check if total coverage is greater then 60
        shell: bash
        run: |
          CODE_COV=$(go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          EXPECTED_CODE_COV=60
          var=$(awk 'BEGIN{ print "'$CODE_COV'"<"'$EXPECTED_CODE_COV'" }')
          if [ "$var" -eq 1 ];then
            echo "Your code coverage is too low. Coverage precentage is: $CODE_COV"
            exit 1
          else
            echo "Your code coverage test passed! Coverage precentage is: $CODE_COV"
            exit 0
          fi